# Imports packages and assign variables

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from IPython.display import display
file_paths = [
    'testData/1.10_A_30s_600ms_3/',
    'testData/2.50_A_30s_600ms_3/',
    'testData/3.90_A_30s_600ms_3/',
    'testData/4.130_A_30s_600ms_3/',
    'testData/5.60_A_30s_200ms_3/',
    'testData/6.60_A_30s_500ms_3/',
    'testData/7.60_A_30s_800ms_3/',
    'testData/8.60_A_30s_1100ms_3/',
    'testData/9.60_A_5s_600ms_3/',
    'testData/10.60_A_20s_600ms_3/',
    'testData/11.60_A_35s_600ms_3/',
    'testData/12.60_A_50s_600ms_3/',
    'testData/13.60_A_30s_600ms_2/',
    'testData/14.60_A_30s_600ms_4/',
    'testData/15.60_A_30s_600ms_6/',
    'testData/16.60_A_30s_600ms_8/',
    'testData/17.60_A_30s_600ms_3/',
    'testData/18.60_A+NA+AZA_30s_600ms_3/',
    'testData/19.60_A+NA_30s_600ms_3/',
    'testData/20.60_A+AZA_30s_600ms_3/',
    'testData/22.10_A+NA+AZA_30s_600ms_3/',
    'testData/23.130_A+NA+AZA_30s_600ms_3/',
    'testData/24.60_A+NA+AZA_30s_200ms_3/',
    'testData/25.60_A+NA+AZA_30s_1100ms_3/',
    'testData/26.60_A+NA+AZA_5s_600ms_3/',
    'testData/27.60_A+NA+AZA_50s_600ms_3/',
    'testData/28.60_A+NA+AZA_30s_600ms_2/',
    'testData/29.60_A+NA+AZA_30s_600ms_8/',
]

labels = [ _[12:-1] if _ [11] == '.' else _[11:-1] for _ in file_paths ]

# Get association rules

In [2]:
def create_low_high_columns(df, column_names):
    new_df = pd.DataFrame()
    i = 0
    for col in column_names:
        non_zero_values = df[df[col] != 0][col]
        threshold = non_zero_values.median()
        high_col_name = f'high_{col}'
        new_df[high_col_name] = df[col].apply(lambda x: 1 if  x >= threshold else 0).astype(bool)
        i +=1
    return new_df

def association():
  for test_dir in file_paths:
    df_path = f'{test_dir}/stockApp_merged_data.csv'
    df = pd.read_csv(df_path)
    column_names = [
    'application_time', 'database_time', 'api_time', 'application_time_trade', 'database_time_trade','cpu_usage_db_test', 'cpu_usage_db', 'cpu_usage_transaction', 'cpu_usage_web'
]
    df_bin = create_low_high_columns(df, column_names)
    frequent_itemsets = apriori(df_bin, min_support=0.3, use_colnames=True)
    rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)
    important_rules = rules[rules['lift'] > 1.2]
    important_rules = important_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
    if len(important_rules.index):
        important_rules = important_rules[important_rules['antecedents'].apply(lambda x: len(x) <= 2)]
    if len(important_rules.index):
        important_rules = important_rules[important_rules['consequents'].apply(lambda x: len(x) <= 2)]
    important_rules['support'] = important_rules['support'].round(2)
    important_rules['confidence'] = important_rules['confidence'].round(2)
    important_rules['lift'] = important_rules['lift'].round(2)
    important_rules['antecedents'] = important_rules['antecedents'].apply(lambda x: ', '.join(list(x)))
    important_rules['consequents'] = important_rules['consequents'].apply(lambda x: ', '.join(list(x)))
    print(test_dir[9:-1])
    if len(important_rules.index):
        with pd.option_context('display.max_rows', min(len(important_rules.index),300), 'display.max_columns', 10):
            display(important_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])
    else:
        print('\n')
association()

1.10_A_30s_600ms_3

             antecedents            consequents  support  confidence  lift
0  high_application_time     high_database_time     0.48        0.95  1.72
1     high_database_time  high_application_time     0.48        0.86  1.72

2.50_A_30s_600ms_3


3.90_A_30s_600ms_3

             antecedents            consequents  support  confidence  lift
0  high_application_time     high_database_time     0.47        0.93  1.68
1     high_database_time  high_application_time     0.47        0.84  1.68

4.130_A_30s_600ms_3

             antecedents            consequents  support  confidence  lift
0  high_application_time     high_database_time     0.46        0.92  1.61
1     high_database_time  high_application_time     0.46        0.81  1.61

5.60_A_30s_200ms_3


6.60_A_30s_500ms_3


7.60_A_30s_800ms_3


8.60_A_30s_1100ms_3

             antecedents            consequents  support  confidence  lift
0  high_application_time     high_database_time     0.46        0.93  1.85
1     high_database_time  high_application_time     0.46        0.92  1.85

9.60_A_5s_600ms_3

             antecedents            consequents  support  confidence  lift
0  high_application_time     high_database_time     0.49        0.98  1.71
1     high_database_time  high_application_time     0.49        0.85  1.71

10.60_A_20s_600ms_3

             antecedents            consequents  support  confidence  lift
0  high_application_time     high_database_time     0.47        0.94  1.78
1     high_database_time  high_application_time     0.47        0.89  1.78

11.60_A_35s_600ms_3


12.60_A_50s_600ms_3


13.60_A_30s_600ms_2


14.60_A_30s_600ms_4


15.60_A_30s_600ms_6


16.60_A_30s_600ms_8


17.60_A_30s_600ms_3


18.60_A+NA+AZA_30s_600ms_3

,antecedents,consequents,support,confidence,lift
6,high_cpu_usage_web,high_cpu_usage_db_test,0.41,0.82,1.64
7,high_cpu_usage_db_test,high_cpu_usage_web,0.41,0.82,1.64
9,"high_cpu_usage_web, high_database_time",high_cpu_usage_db_test,0.41,0.82,1.64
11,"high_database_time, high_cpu_usage_db_test",high_cpu_usage_web,0.41,0.82,1.64
12,high_cpu_usage_web,"high_database_time, high_cpu_usage_db_test",0.41,0.82,1.64
13,high_cpu_usage_db_test,"high_cpu_usage_web, high_database_time",0.41,0.82,1.64
15,"high_cpu_usage_web, high_cpu_usage_db",high_cpu_usage_db_test,0.34,0.89,1.78
16,"high_cpu_usage_web, high_cpu_usage_db_test",high_cpu_usage_db,0.34,0.82,1.63
17,"high_cpu_usage_db, high_cpu_usage_db_test",high_cpu_usage_web,0.34,0.89,1.79
22,"high_cpu_usage_web, high_cpu_usage_db_test","high_database_time, high_cpu_usage_db",0.34,0.82,1.63
23,"high_cpu_usage_web, high_cpu_usage_db","high_database_time, high_cpu_usage_db_test",0.34,0.89,1.78
24,"high_cpu_usage_db, high_cpu_usage_db_test","high_cpu_usage_web, high_database_time",0.34,0.89,1.79

19.60_A+NA_30s_600ms_3


20.60_A+AZA_30s_600ms_3

,antecedents,consequents,support,confidence,lift
9,"high_cpu_usage_web, high_cpu_usage_db",high_cpu_usage_db_test,0.33,0.88,1.76
10,"high_cpu_usage_web, high_cpu_usage_db_test",high_cpu_usage_db,0.33,0.89,1.77
11,"high_cpu_usage_db, high_cpu_usage_db_test",high_cpu_usage_web,0.33,0.90,1.79
16,"high_cpu_usage_web, high_cpu_usage_db_test","high_database_time, high_cpu_usage_db",0.33,0.89,1.77
17,"high_cpu_usage_web, high_cpu_usage_db","high_database_time, high_cpu_usage_db_test",0.33,0.88,1.76
18,"high_cpu_usage_db, high_cpu_usage_db_test","high_cpu_usage_web, high_database_time",0.33,0.90,1.79

22.10_A+NA+AZA_30s_600ms_3


23.130_A+NA+AZA_30s_600ms_3


24.60_A+NA+AZA_30s_200ms_3


25.60_A+NA+AZA_30s_1100ms_3


26.60_A+NA+AZA_5s_600ms_3


27.60_A+NA+AZA_50s_600ms_3


28.60_A+NA+AZA_30s_600ms_2


29.60_A+NA+AZA_30s_600ms_8